### ISSUE TITLE
Proper Database solution

### ISSUE THREAD

**Issue by tdh911** [rthotakura97/decentralized-database#17]
DynamoDB, MongoDB, MySQL, Cassandra, Redis, ...
Preferably something free.

**Comment by tdh911** [comment]
Let's actually implement this in when we finish the backend instead of just doing in memory

**Comment by tdh911** [comment]
This should be used both for the data blocks as well as the file data (we currently are using Guava Multimap for that).

**Comment by tdh911** [comment]
Actually, wouldn't it be redundant to use a preexisting database as the backend of something we're doing? We should just write that part ourselves.

**Comment by rthotakura97** [comment]
We should implement the database ourselves, but have our database hosted by a different service. Using a pre-existing database is redundant.

**Comment by tdh911** [comment]
This is not in scope for this package.
